### ISSUE TITLE
test timed out after xxxx milliseconds

### ISSUE THREAD

**Issue by fpj** [zk1931/jzab#215]
There is probably something wrong with my local config, but I'm getting a lot of errors like this when running the tests:

```
java.lang.Exception: test timed out after 20000 milliseconds
	at java.net.InetAddress.getLocalHost(InetAddress.java:1456)
	at com.github.zk1931.jzab.TestBase.getHostPort(TestBase.java:98)
	at com.github.zk1931.jzab.TestBase.getUniqueHostPort(TestBase.java:109)
	at com.github.zk1931.jzab.SnapshotTest.testSnapshotCluster(SnapshotTest.java:185)
```

Any idea of what could be wrong with my local address? This is happening on mac os, but I'll check on linux as well.

**Comment by EasonLiao** [comment]
@fpj,  I haven't seen this  before, could you open the log file at ```target/surefire-reports/com.github.zk1931.jzab.$TEST_NAME-out.txt``` and see if there's any clue?
